In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import time

In [ ]:
# orig_phat_df = pd.read_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/phat_f475W_f814W_table.csv')
# orig_phast_df = pd.read_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/phast_f475W_f814W_table.csv')
# phat_df.head()

# shared_cols = orig_phat_df.columns.intersection(orig_phast_df.columns).tolist()
# orig_m31_df = pd.concat([orig_phat_df[shared_cols], orig_phast_df[shared_cols]], ignore_index=True)
# orig_m31_df.drop_duplicates(inplace=True)
# orig_m31_df.reset_index(drop=True, inplace=True)
# orig_m31_df.to_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/original_m31_table.csv', index=False)
# orig_m31_df.head()

In [ ]:
reduced_phat_df = pd.read_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/reduced_phat_table.csv', nrows=100)
reduced_phast_df = pd.read_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/reduced_phast_table.csv', nrows=100)
reduced_phat_df.head()

,Unnamed: 0,ra,dec,f475w_vega,f475w_snr,f475w_crowd,f475w_sharp,f475w_flag,f814w_vega,f814w_snr,f814w_crowd,f814w_sharp,f814w_flag,f814w_vega_ecorr,f475w_vega_ecorr,f475w-f814w_ecorr
0,0,10.772439,41.203526,15.754,324.2,0.000,-0.023,1,14.146,562.5,0.000,-0.034,1,14.24732,15.96004,1.71272
1,1,10.861762,41.237756,15.986,80.1,0.019,0.016,1,15.214,50.3,0.017,-0.050,1,15.31532,16.19204,0.87672
2,2,10.763488,41.193805,15.836,253.7,0.004,0.001,1,14.699,453.0,0.002,-0.003,1,14.80032,16.04204,1.24172
3,3,10.840829,41.205419,16.755,127.7,0.000,-0.048,1,15.116,435.0,0.001,-0.010,1,15.21732,16.96104,1.74372
4,4,10.786556,41.173557,16.706,100.7,0.027,0.010,1,15.028,322.5,0.015,0.019,1,15.12932,16.91204,1.78272

In [11]:
reduced_phat_catalog_df = pd.read_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/reduced_phat_catalog.csv', nrows=100)
reduced_phast_catalog_df = pd.read_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/reduced_phast_catalog.csv', nrows=100)
reduced_phat_catalog_df.head()

,Unnamed: 0,ra,dec,f475w_vega,f475w_snr,f475w_crowd,f475w_sharp,f475w_flag,f814w_vega,f814w_snr,f814w_crowd,f814w_sharp,f814w_flag,f814w_vega_ecorr,f475w_vega_ecorr,f475w-f814w_ecorr,f475w_vega-f814w_vega
0,0,10.772439,41.203526,15.754,324.2,0.000,-0.023,1,14.146,562.5,0.000,-0.034,1,14.24732,15.96004,1.71272,1.608
1,1,10.861762,41.237756,15.986,80.1,0.019,0.016,1,15.214,50.3,0.017,-0.050,1,15.31532,16.19204,0.87672,0.772
2,2,10.763488,41.193805,15.836,253.7,0.004,0.001,1,14.699,453.0,0.002,-0.003,1,14.80032,16.04204,1.24172,1.137
3,3,10.840829,41.205419,16.755,127.7,0.000,-0.048,1,15.116,435.0,0.001,-0.010,1,15.21732,16.96104,1.74372,1.639
4,4,10.786556,41.173557,16.706,100.7,0.027,0.010,1,15.028,322.5,0.015,0.019,1,15.12932,16.91204,1.78272,1.678

In [30]:
start_time = time.time()
phat_gst_catalog_df = pd.read_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/4GYRS_RGB_AGB_isochrones/phat_gst_optical_catalog.csv')
phast_gst_catalog_df = pd.read_csv('/Users/mmckay/phd_projects/analysis_routine/DATA/4GYRS_RGB_AGB_isochrones/phast_gst_optical_catalog.csv')
phast_gst_catalog_df.head()


shared_cols = phat_gst_catalog_df.columns.intersection(phast_gst_catalog_df.columns).tolist()
m31_gst_catalog_df = pd.concat([phat_gst_catalog_df[shared_cols], phast_gst_catalog_df[shared_cols]], ignore_index=True)
print(f"Number of rows in combined M31 GST catalog before deduplication: {len(m31_gst_catalog_df)}")
m31_gst_catalog_df.drop_duplicates(inplace=True)
print(f"Number of rows in combined M31 GST catalog after deduplication: {len(m31_gst_catalog_df)}")
m31_gst_catalog_df.reset_index(drop=True, inplace=True)
m31_gst_catalog_df.head()
m31_gst_catalog_df.to_csv(f'/Users/mmckay/phd_projects/analysis_routine/DATA/m31_photometry_gst_optical_catalog_{len(m31_gst_catalog_df)}.csv', index=False)
end_time = time.time()
print(f"Time taken to merge and save M31 GST catalog: {(end_time - start_time)/60:.8f} minutes")

Number of rows in combined M31 GST catalog before deduplication: 13689259
Number of rows in combined M31 GST catalog after deduplication: 13689259
Time taken to merge and save M31 GST catalog: 4.50035173 minutes